# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  - name: ConveRTTokenizer
  - name: ConveRTFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "SklearnIntentClassifier"
    C: [1, 2, 5, 10, 20, 100]
    kernels: ["linear"]
    "gamma": [0.1]
    "max_cross_validation_folds": 5
    "scoring_function": "f1_weighted"
